name: Test

on:
  push:
  pull_request:

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fmt
        if: matrix.os != 'windows-latest'
        run: diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go'| grep -v "/vendor/"))

      - name: vet
        run: go vet ./...